apiVersion: "nuclio.io/v1"
kind: NuclioFunction
metadata:
  name: get_worker_id
spec:
  handler: main:handler
  runtime: python:3.6
  minReplicas: 3
  maxReplicas: 3
  description: Just returns worker id with a job from 3 workers
  image: get_worker_id:latest
  triggers:
    default-http:
      class: ""
      kind: http
      name: default-http
      maxWorkers: 1
      attributes:
        port: 32003
  resources:
    limits:
      nvidia.com/gpu: 1

# nuctl deploy execute_command --run-image execute_command:latest --runtime python:3.6 --handler main:handler --platform local --resource-limit nvidia.com/gpu=1