apiVersion: "nuclio.io/v1"
kind: NuclioFunction
metadata:
  name: post_http
spec:
  handler: main:handler
  runtime: python:3.6
  minReplicas: 1
  maxReplicas: 1
  description: Post something to the specified http server
  image: post_http:latest
  triggers:
    default-http:
      class: ""
      kind: http
      name: default-http
      maxWorkers: 1
      attributes:
        port: 32002
  resources:
    limits:
      nvidia.com/gpu: 1
  build:
    commands:
      - pip3 install requests

# nuctl deploy execute_command --run-image execute_command:latest --runtime python:3.6 --handler main:handler --platform local --resource-limit nvidia.com/gpu=1