apiVersion: "nuclio.io/v1"
kind: NuclioFunction
metadata:
  name: get_context
spec:
  handler: main:handler
  runtime: python:3.6
  minReplicas: 1
  maxReplicas: 1
  description: Just returns the context and event object, because why not
  image: get_context:latest
  triggers:
    default-http:
      class: ""
      kind: http
      name: default-http
      maxWorkers: 1
      attributes:
        ingresses:
          "0":
            host: nuclio.local
            paths:
              - /get_context
  resources:
    limits:
      nvidia.com/gpu: 1

# nuctl deploy execute_command --run-image execute_command:latest --runtime python:3.6 --handler main:handler --platform local --resource-limit nvidia.com/gpu=1