version: "3.7"
services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ACCESS_KEY: "minio-admin"
      MINIO_SECRET_KEY: "minio-admin"
    command: server /data
